version: "3.9"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: ../infrastructure/Dockerfile.frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./frontend:/app
      - /app/node_modules

  backend:
    build:
      context: .
      dockerfile: infrastructure/Dockerfile.backend
    ports:
      - "8000:8000"
    env_file:
      - backend/.env
    volumes:
      - ./backend:/app
